package salon.sales.application.service;

import org.springframework.stereotype.Service;
import salon.sales.application.port.in.AcceptOffer;
import salon.sales.application.port.in.ActivateOrderOnDeposit;
import salon.sales.application.port.in.ReceiveSpecificationUseCase;
import salon.sales.application.port.in.ReleaseVehicle;
import salon.sales.application.command.ScheduleHandoverCommand;
import salon.sales.application.port.in.ScheduleHandover;
import salon.sales.application.command.StartConfiguratorSessionCommand;
import salon.sales.application.port.in.StartConfigurator;
import salon.sales.application.port.in.SynchronizeSpecificationPriceUseCase;
import salon.sales.application.port.out.BillingIntegration;
import salon.sales.application.port.out.CustomerDatabaseRepository;
import salon.sales.application.port.out.InventoryIntegration;
import salon.sales.application.port.out.OfferDatabaseRepository;
import salon.sales.application.port.out.OrderDatabaseRepository;
import salon.sales.application.port.out.SpecificationPriceReadModelPort;
import salon.sales.application.domain.event.ConfiguratorSessionInitiatedEvent;
import salon.sales.application.domain.exception.OfferNotFoundException;
import salon.sales.application.domain.exception.OrderNotFoundException;
import salon.sales.application.domain.exception.SpecificationNotFoundException;
import salon.sales.application.domain.model.customer.Customer;
import salon.sales.application.domain.model.customer.CustomerId;
import salon.sales.application.domain.model.offer.Offer;
import salon.sales.application.domain.model.offer.OfferFactory;
import salon.sales.application.domain.model.offer.OfferId;
import salon.sales.application.domain.model.offer.OfferState;
import salon.sales.application.domain.model.order.Order;
import salon.sales.application.domain.model.order.OrderFactory;
import salon.sales.application.domain.model.order.OrderState;
import salon.common.application.EventPublisher;
import salon.common.model.Money;
import salon.common.model.OrderId;
import salon.common.model.SpecificationId;

import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * The centralized application service of the Sales and CRM Context — the "SalesService" node
 * z docs/Architecture/SalesArchitecture.md (PDF rozdz. 3.3.3, Rys. 23).
 *
 * It handles the use cases UC-CRM-01..05:
 *   startConfiguratorSession (UC-CRM-01, bezstanowy wyzwalacz),
 *   generateOffer            (UC-CRM-02, price from the local read model — event-carried),
 *   acceptOfferAndCreateOrder(UC-CRM-03, validity/conversion rules in the Offer aggregate),
 *   activateOnDeposit        (UC-CRM-03 part 2 — activation after a posted payment),
 *   markOrderAsReadyForHandover + scheduleHandover (UC-CRM-04),
 *   confirmHandover          (UC-CRM-05, the ReleaseVehicle command through InventoryIntegration),
 *   cancelOrder, expireOutdatedOffers, revertHandoverOnInventoryError (kompensata A1).
 *
 * The business rules remain in the aggregates (Offer/Order) and factories (OfferFactory/
 * OrderFactory); here there is only orchestration: fetching the aggregate, invoking the method,
 * saving and publishing the events GENERATED BY THE AGGREGATE (publishAll after saving).
 * The integration ports may be null in partial runs (unit tests).
 */
@Service
public class SalesService
        implements StartConfigurator, ReceiveSpecificationUseCase, AcceptOffer,
        ActivateOrderOnDeposit, ScheduleHandover, ReleaseVehicle,
        SynchronizeSpecificationPriceUseCase {

    private final CustomerDatabaseRepository customerRepository;
    private final OfferDatabaseRepository offerRepository;
    private final OrderDatabaseRepository orderRepository;
    private final EventPublisher eventPublisher;
    private final SpecificationPriceReadModelPort specificationPriceReadModel;
    private final InventoryIntegration inventoryPort;
    private final BillingIntegration billingPort;

    private final OfferFactory offerFactory = new OfferFactory();
    private final OrderFactory orderFactory = new OrderFactory();

    public SalesService(CustomerDatabaseRepository customerRepository,
                           OfferDatabaseRepository offerRepository,
                           OrderDatabaseRepository orderRepository,
                           EventPublisher eventPublisher,
                           SpecificationPriceReadModelPort specificationPriceReadModel,
                           InventoryIntegration inventoryPort,
                           BillingIntegration billingPort) {
        this.customerRepository = customerRepository;
        this.offerRepository = offerRepository;
        this.orderRepository = orderRepository;
        this.eventPublisher = eventPublisher;
        this.specificationPriceReadModel = specificationPriceReadModel;
        this.inventoryPort = inventoryPort;
        this.billingPort = billingPort;
    }

    // --- Customer (CRM) ---

    /** Registering/saving the customer in the Sales context. */
    public void registerCustomer(Customer customer) {
        if (customer == null) {
            throw new IllegalArgumentException("customer must not be null.");
        }
        customerRepository.save(customer);
    }

    // --- UC-CRM-01: uruchomienie sesji konfiguratora ---

    /**
     * A stateless trigger (PDF chapter 3.3.3): it creates no aggregates — it generates the session
     * identifier and emits the InitiateConfiguratorSession event, to which the Catalog Context reacts.
     */
    @Override
    public String startConfiguratorSession(StartConfiguratorSessionCommand command) {
        if (command == null) {
            throw new IllegalArgumentException("command must not be null.");
        }
        String sessionId = "CFG-" + UUID.randomUUID();
        eventPublisher.publish(new ConfiguratorSessionInitiatedEvent(
                UUID.randomUUID(),
                sessionId,
                command.customerId(),
                command.salespersonId(),
                Instant.now()));
        return sessionId;
    }

    // --- UC-CRM-02: generating the proforma offer ---

    /**
     * The specification pricing comes from the Sales local read model (fed by the
     * SpecificationCompleted event from the Catalog) — without synchronously querying another context.
     * The customer data is provided by the Salesperson (customerId). It delegates creation to {@link OfferFactory};
     * the offer is published ("Created") and ready to present to the customer.
     */
    @Override
    public OfferId generateOffer(String customerId, String specificationId) {
        if (customerId == null || customerId.isBlank()) {
            throw new IllegalArgumentException("customerId must not be blank.");
        }
        if (specificationId == null || specificationId.isBlank()) {
            throw new IllegalArgumentException("specificationId must not be blank.");
        }
        // UC-CRM-02, step 3: the catalog price comes from the local read model fed by
        // the SpecificationCompleted event (event-carried state transfer) — without synchronous
        // querying the Catalog. No entry = the event has not arrived yet.
        Money basePrice = specificationPriceReadModel.findPrice(new SpecificationId(specificationId))
                .orElseThrow(() -> new SpecificationNotFoundException(
                        "No pricing for specification " + specificationId
                                + " — the SpecificationCompleted event has not arrived yet."));

        Offer offer = offerFactory.createOffer(
                new CustomerId(customerId), new SpecificationId(specificationId), basePrice);
        offer.publishOffer();
        offerRepository.save(offer);
        return offer.id();
    }

    /**
     * UC-CRM-02 (precondition): saving the specification's catalog pricing from the received
     * SpecificationCompleted event into the Sales local read model.
     */
    @Override
    public void registerSpecificationPrice(String specificationId, Money price) {
        if (specificationId == null || specificationId.isBlank()) {
            throw new IllegalArgumentException("specificationId must not be blank.");
        }
        if (price == null) {
            throw new IllegalArgumentException("price must not be null.");
        }
        this.specificationPriceReadModel.saveSpecificationPrice(
                new SpecificationId(specificationId), price);
    }

    // --- UC-CRM-03 (part 1): offer acceptance and order creation ---

    /**
     * The validity and conversion rules are enforced by the Offer aggregate (accept/toSnapshot);
     * the order is built by {@link OrderFactory} from the immutable offer snapshot.
     * After saving, the whole batch of aggregate events is published (OrderPlacedEvent),
     * and Inventory receives the order to allocate a vehicle/production slot.
     */
    @Override
    public String acceptOfferAndCreateOrder(OfferId offerId) {
        if (offerId == null) {
            throw new IllegalArgumentException("offerId must not be null.");
        }
        Offer offer = offerRepository.findById(offerId)
                .orElseThrow(() -> new OfferNotFoundException(offerId.value()));

        offer.accept();
        Order order = orderFactory.createFromOffer(offer.id(), offer.toSnapshot());

        offerRepository.save(offer);
        orderRepository.save(order);
        eventPublisher.publishAll(order.pullDomainEvents());

        if (inventoryPort != null) {
            inventoryPort.allocateVehicleOrProductionSlot(order.id().value());
        }
        return order.id().value();
    }

    // UC-CRM-03, scenario A1: the customer rejects the offer — nothing is emitted.
    public void rejectOffer(OfferId offerId) {
        if (offerId == null) {
            throw new IllegalArgumentException("offerId must not be null.");
        }
        Offer offer = offerRepository.findById(offerId)
                .orElseThrow(() -> new OfferNotFoundException(offerId.value()));
        offer.reject();
        offerRepository.save(offer);
    }

    // --- UC-CRM-03 (part 2): activation after the payment is posted (Fig. 19/20 PDF) ---

    @Override
    public void activateOnDeposit(String orderId) {
        if (orderId == null || orderId.isBlank()) {
            throw new IllegalArgumentException("orderId must not be blank.");
        }
        Optional<Order> found = orderRepository.findById(new OrderId(orderId));
        if (found.isEmpty()) {
            System.out.println("[SalesService] No order for id " + orderId + " — deposit ignored.");
            return;
        }
        Order order = found.get();
        if (order.state() != OrderState.DRAFT_CREATED && order.state() != OrderState.DRAFT) {
            System.out.println("[SalesService] Order " + orderId
                    + " already active (" + order.state() + ") — deposit event ignored.");
            return;
        }
        order.activate();
        orderRepository.save(order);
        eventPublisher.publishAll(order.pullDomainEvents());
    }

    // --- UC-CRM-04: vehicle readiness and scheduling the handover ---

    /**
     * Steps 1-2: reaction to VehicleReadyForHandoverEvent from Inventory — the order transitions
     * to "Ready for handover" and publishes OrderReadyForHandoverEvent (notifying the Salesperson).
     */
    public void markOrderAsReadyForHandover(OrderId orderId) {
        Order order = loadOrder(orderId);
        order.markAsReadyForHandover();
        orderRepository.save(order);
        eventPublisher.publishAll(order.pullDomainEvents());
    }

    /** Steps 4-5: the Salesperson enters the agreed pickup date -> "Handover scheduled". */
    @Override
    public void scheduleHandover(ScheduleHandoverCommand command) {
        if (command == null) {
            throw new IllegalArgumentException("command must not be null.");
        }
        Order order = loadOrder(new OrderId(command.orderId()));
        // Input validation — an invalid date is rejected before anything reaches the database (UC-CRM-04).
        if (command.handoverDate().isBefore(LocalDate.now())) {
            throw new IllegalArgumentException("Handover date cannot be in the past");
        }
        order.scheduleHandover(command.handoverDate());
        orderRepository.save(order);
        eventPublisher.publishAll(order.pullDomainEvents());
    }

    // --- UC-CRM-05: registering the physical vehicle handover ---

    /**
     * The order transitions to "Completed" (Order.confirmHandover), Inventory receives
     * the ReleaseVehicle command (removing the physical car from stock — UC-INW-06), and Billing
     * closes the final balance. An Inventory error aborts the process BEFORE saving (the order
     * cannot be marked as completed while there is a stock lock).
     */
    @Override
    public void confirmHandover(OrderId orderId) {
        Order order = loadOrder(orderId);
        order.confirmHandover();

        if (inventoryPort != null) {
            inventoryPort.releasePhysicalVehicle(order.vehicleId());
        }
        if (billingPort != null) {
            billingPort.closeOrderBalance(order.id().value());
        }

        orderRepository.save(order);
        eventPublisher.publishAll(order.pullDomainEvents());
    }

    /**
     * UC-CRM-05, A1: Inventory refused the release (VehicleInventoryReleasedError) — compensation
     * (saga): reverting the order to "Ready for handover" (the handover date is cleared).
     */
    public void revertHandoverOnInventoryError(String orderId) {
        Order order = loadOrder(new OrderId(orderId));
        order.revertToReadyForHandover();
        orderRepository.save(order);
        eventPublisher.publishAll(order.pullDomainEvents());
    }

    // --- Cancelling the order (customer cancellation) ---

    public void cancelOrder(String orderId, String reason) {
        Order order = loadOrder(new OrderId(orderId));
        order.cancelOrder(reason);
        orderRepository.save(order);
        eventPublisher.publishAll(order.pullDomainEvents());
    }

    // --- Cron: expiring overdue offers (validityDate < today) ---

    /**
     * Offers past their validity date can no longer be accepted (the rule
     * is also enforced by the aggregate in accept()); the periodic task rejects expired,
     * published offers so they do not linger in the active commercial flow.
     */
    public void expireOutdatedOffers() {
        LocalDate today = LocalDate.now();
        List<Offer> offers = offerRepository.findAll();
        for (int i = 0; i < offers.size(); i++) {
            Offer offer = offers.get(i);
            if (offer.state() == OfferState.PUBLISHED
                    && offer.validityDate().isBefore(today)) {
                offer.reject();
                offerRepository.save(offer);
            }
        }
    }

    // --- pomocnicze ---

    private Order loadOrder(OrderId orderId) {
        if (orderId == null) {
            throw new IllegalArgumentException("orderId must not be null.");
        }
        return orderRepository.findById(orderId)
                .orElseThrow(() -> new OrderNotFoundException(
                        "Order with ID " + orderId.value() + " not found"));
    }
}
